### ISSUE TITLE
Blogpost not displaying category

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/blog#24]
This recent post is in the 'Open Source' category, but is not indicating that in the header:

https://blog.scottlogic.com/2022/11/15/activitypub-the-open-standard-that-makes-mastodon-special.html

**Comment by ColinEberhardt** [comment]
Here's another one https://blog.scottlogic.com/2022/11/18/why-you-should-get-the-right-people-in-the-room-from-the-start.html

**Comment by ColinEberhardt** [comment]
It is likely to be related to this bug https://github.com/ScottLogic/blog/issues/4

**Comment by Jahoe** [comment]
The category logic has been revamped in #30 - the issue was that we originally looked for the category of index [1] but for this post, the author has been put as the second category (0 based) and seeing as their name isn't a predefined category in `categories.yml` it threw a parse error and showed it as blank.
